challenge: challenge.o FileNotFoundError.o FileNotFoundError.h
	g++ -o challenge challenge.o FileNotFoundError.o
challenge.o: challenge.cpp FileNotFoundError.h
	g++ -c challenge.cpp
FileNotFoundError.o: FileNotFoundError.cpp FileNotFoundError.h
	g++ -c FileNotFoundError.cpp
